// <auto-generated />
using System;
using FinanceMove.Modules.Transactions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceMove.Modules.Transactions.Migrations
{
    [DbContext(typeof(TransactionsDbContext))]
    partial class TransactionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("transactions")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceMove.Modules.Transactions.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("archived");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<bool>("System")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("system");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("UserId", "Name", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_category_name")
                        .HasFilter("archived = false");

                    b.ToTable("category", "transactions");
                });

            modelBuilder.Entity("FinanceMove.Modules.Transactions.InstallmentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("description");

                    b.Property<short>("Installments")
                        .HasColumnType("smallint")
                        .HasColumnName("installments");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_amount");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_installment_group");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_installment_group_user");

                    b.ToTable("installment_group", "transactions");
                });

            modelBuilder.Entity("FinanceMove.Modules.Transactions.RecurrenceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("frequency");

                    b.Property<DateOnly>("NextRunOn")
                        .HasColumnType("date")
                        .HasColumnName("next_run_on");

                    b.Property<short>("ReferenceDay")
                        .HasColumnType("smallint")
                        .HasColumnName("reference_day");

                    b.Property<short?>("ReferenceMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("reference_month");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recurrence_rule");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_recurrence_rule_category_id");

                    b.HasIndex("NextRunOn")
                        .HasDatabaseName("ix_recurrence_next")
                        .HasFilter("active");

                    b.ToTable("recurrence_rule", "transactions", t =>
                        {
                            t.HasCheckConstraint("ck_recurrence_day", "(frequency = 'Weekly' AND reference_day BETWEEN 1 AND 7 AND reference_month IS NULL)\nOR (frequency = 'Monthly' AND reference_day BETWEEN 1 AND 28 AND reference_month IS NULL)\nOR (frequency = 'Yearly' AND reference_day BETWEEN 1 AND 28 AND reference_month BETWEEN 1 AND 12)");
                        });
                });

            modelBuilder.Entity("FinanceMove.Modules.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DestinationAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_account_id");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("external_id");

                    b.Property<Guid?>("InstallmentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("installment_group_id");

                    b.Property<short?>("InstallmentNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("installment_number");

                    b.Property<short?>("InstallmentTotal")
                        .HasColumnType("smallint")
                        .HasColumnName("installment_total");

                    b.Property<Guid?>("RecurrenceRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurrence_rule_id");

                    b.Property<string>("StatementMonth")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("statement_month");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_transaction");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transaction_category_id");

                    b.HasIndex("InstallmentGroupId")
                        .HasDatabaseName("ix_transaction_installment_group_id");

                    b.HasIndex("RecurrenceRuleId")
                        .HasDatabaseName("ix_transaction_recurrence_rule_id");

                    b.HasIndex("UserId", "Date")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_transaction_list");

                    b.HasIndex("UserId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_transaction_external")
                        .HasFilter("external_id IS NOT NULL");

                    b.HasIndex("UserId", "AccountId", "Date")
                        .HasDatabaseName("ix_transaction_account");

                    b.HasIndex("UserId", "CategoryId", "Date")
                        .HasDatabaseName("ix_transaction_category")
                        .HasFilter("status = 'Confirmed'");

                    b.HasIndex("UserId", "DestinationAccountId", "Date")
                        .HasDatabaseName("ix_transaction_dest")
                        .HasFilter("destination_account_id IS NOT NULL");

                    b.ToTable("transaction", "transactions", t =>
                        {
                            t.HasCheckConstraint("ck_transaction_amount", "amount > 0");

                            t.HasCheckConstraint("ck_transaction_installment", "(installment_group_id IS NULL AND installment_number IS NULL AND installment_total IS NULL)\nOR\n(installment_group_id IS NOT NULL AND installment_number BETWEEN 1 AND installment_total)");

                            t.HasCheckConstraint("ck_transaction_shape", "(\"type\" = 'Transfer'\n   AND destination_account_id IS NOT NULL\n   AND destination_account_id <> account_id\n   AND category_id IS NULL)\nOR\n(\"type\" IN ('Income','Expense')\n   AND destination_account_id IS NULL\n   AND category_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("FinanceMove.Modules.Transactions.RecurrenceRule", b =>
                {
                    b.HasOne("FinanceMove.Modules.Transactions.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recurrence_rule_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceMove.Modules.Transactions.Transaction", b =>
                {
                    b.HasOne("FinanceMove.Modules.Transactions.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transaction_category_category_id");

                    b.HasOne("FinanceMove.Modules.Transactions.InstallmentGroup", null)
                        .WithMany()
                        .HasForeignKey("InstallmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_transaction_installment_group_installment_group_id");

                    b.HasOne("FinanceMove.Modules.Transactions.RecurrenceRule", null)
                        .WithMany()
                        .HasForeignKey("RecurrenceRuleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transaction_recurrence_rule_recurrence_rule_id");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
